### ISSUE TITLE
Maybe we can support config service discovery

### ISSUE THREAD

**Issue by gjflsl** [prometheus/blackbox_exporter#219]
Hi.
I think maybe we can add configs discovered via service discovery like the SD of prometheus.
So, we can add any modules config by file or consul.

**Comment by brian-brazil** [comment]
Service discovery is the responsibility of Prometheus, you can use the SD there to figure out the hosts.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by gjflsl** [comment]
Yes, I see.
Thanks.
