### ISSUE TITLE
How to config POST Req for REST API.

### ISSUE THREAD

**Issue by arunsraga** [prometheus/blackbox_exporter#233]
@Feature Request

I Have tried to check REST API for POST method, i failed to make config properly for prometheus.yml and blackbox.yml.

I followed this link [https://go.hotlibs.com/github.com/prometheus/blackbox_exporter/package](url)

How to configure the prometheus.yml and blackbox.yml for POST method request body.

Please share the document how to use REST methods.

Thank you.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by arunsraga** [comment]
Sorry I was not aware of this group [https://groups.google.com/forum/#!forum/prometheus-users](url), i will post here.

Thank You.
