### ISSUE TITLE
what's the value of icmp

### ISSUE THREAD

**Issue by smallfish01** [prometheus/blackbox_exporter#244]
Hello,
I use "blackbox_exporter" as  monitoring our servers "Ping", I got the ping value from Prometheus, now I need setup this in Grafana,but I don't know how convert the value to Grafana, please check the screenshot as below.
<img width="1275" alt="screen shot 2017-10-11 at 18 03 08" src="https://user-images.githubusercontent.com/4077255/31434435-fa4f4368-aeae-11e7-8ec0-a3c83c0be11e.png">
<img width="1400" alt="screen shot 2017-10-11 at 18 09 21" src="https://user-images.githubusercontent.com/4077255/31434604-5fc12acc-aeaf-11e7-848c-1b1d376e6ece.png">
<img width="1394" alt="screen shot 2017-10-11 at 18 09 31" src="https://user-images.githubusercontent.com/4077255/31434611-63fec98c-aeaf-11e7-88de-991f3a24f90b.png">

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
