### ISSUE TITLE
Specify header with different destination IPs?

### ISSUE THREAD

**Issue by strowi** [prometheus/blackbox_exporter#256]
Hi,

right now i couldn't find a way to test Domains with multiple IPs? Is there a way to send http-requests to specific ips?

greetings,
strowi

**Comment by brian-brazil** [comment]
That's a matter of setting the right target.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
