### ISSUE TITLE
Q: Specific module for a target

### ISSUE THREAD

**Issue by wernight** [prometheus/blackbox_exporter#282]
Is there a simple way (without creating another prober) to have some targets use a specific module? For example for some URL I'd want to check that it contains a certain string.

**Comment by brian-brazil** [comment]
Each module can have its own regexes.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by wernight** [comment]
Thanks, posted https://groups.google.com/forum/#!topic/prometheus-users/YR0-87q2p4U
