### ISSUE TITLE
Forward auth headers to target

### ISSUE THREAD

**Issue by bgagnon** [prometheus/blackbox_exporter#290]
It is currently possible to configure `basic_auth` for the `http` probe using `blackbox.yml`. What about using different credentials depending on the probe target? My use case is for a few dozen targets, each with their specific credentials.

Rather than creating a separate probe _module_ for each target, how about having the option to forward authentication sent to the blackbox exporter to the probed HTTP target instead? The `/probe` endpoint currently disregards the `WWW-Authenticate` header entirely.

One advantage of this is that it moves the configuration of basic auth to the prometheus scrape configuration and, by extension, to the `ServiceMonitor` custom rersource when using [prometheus-operator](https://coreos.com/operators/prometheus/docs/latest/). This adds the extra benefit of storing credentials in `Secret` objects.

Would that be within the scope of what the blackbox exporter can do?

**Comment by bgagnon** [comment]
> You need to create a module per target, just as you'd need to create a different scrape config per basic auth credentials in Prometheus. 

Sure, that works. It's just somewhat redundant because the success/fail conditions are going to be the same for all modules -- only difference would be the credentials. And yet the modules themselves don't know the targets, as this is passed to the `/probe` handler.

It feels odd to have to define separate modules for each target. Why is the target URL not part of a module in that case? I could just `/probe` some specifc ID that holds all the configuration.

> It would also be incorrect to pass on credentials, as they could be for a proxy in front of the blackbox exporter

If a forward proxy used by the blackbox exporter needs authentication (`Proxy-Authenticate`), it needs to be independent of the proxied service's authentication (`WWW-Authenticate`). I agree that the two sets of credentials should not be confused. In my case I'm only interested in the `WWW-Authenticate` header.

> it couldn't work for TLS

How so?

> I'd suggest standardising your credentials for monitoring.

Thanks, but I can't. It's a black box after all :)

**Comment by brian-brazil** [comment]
> Why is the target URL not part of a module in that case?

Because it's expected that you'll run the same module against many, many targets. The targets come from service discovery, which is Prometheus's responsibility.

> How so?

That would be a man in the middle attack against TLS, which is not meant to be possible.

**Comment by bgagnon** [comment]
> Because it's expected that you'll run the same module against many, many target

Which brings us back to this not working if each target needs different credentials.

I don't see a resolution to this issue possible if having additional parameters carried through the probe request itself (via params, headers or body) to share a common module config are out of the question.

**Comment by brian-brazil** [comment]
There are no plans to add any features along those lines.

**Comment by bgagnon** [comment]
Understood. I appreciate the clarity, and thank you for the fast responses.

**Comment by akanshgupta** [comment]
@brian-brazil  can you share the blackbox.yaml config file or any other changes that we need to make if we have common creds for dozen of endpoints we are monitoring.

I am stuck in a scenario and need your help to make a way out of it.

**Comment by AndresPineros** [comment]
Having a shared password across multiple services just seems like a really bad security practice. It is strange that there's this effort to decentralize the Prometheus configuration by having ServiceMonitor and Probe CRDs, but still, we centralize the credentials for different services in a single black box exporter instance.

So now the solution is to basically deploy one blackbox exporter for each service because:
- having a centralized component goes against automation
- having shared passwords goes against security.

Anyways... I guess this is something I'll hear often now: "I just deployed this new service, I need to remember to create the new module on the blackbox exporter with the new basic auth credentials". Or "Please tell me again... why are we consuming all these unnecessary resources by having one blackbox exporter per public endpoint?"

Forwarding auth credentials from the ServiceMonitor or the Probe to the blackbox seems like the best solution to me.

**Comment by dgl** [comment]
@AndresPineros -- you're commenting on an issue in blackbox_exporter rather than prometheus-operator. The CRDs you mention are provided by prometheus-operator, there's a mention of a "phase 3" in https://github.com/prometheus-operator/prometheus-operator/pull/2832 to implement some configuration management for this on the operator side. It might be more constructive to follow up with them about the status of that.

In general Prometheus is providing the underlying tools which components like prometheus-operator then provide management on top of, ranting here isn't going to help. It should also be quite easy to write some templating that defines the module in one place, Prometheus components don't generally provide templating like that as there are different options, but if you're using prometheus-operator you can add a definition for a blackbox exporter with jsonnet that defines modules as you desire.

**Comment by AndresPineros** [comment]
@dgl Yeha, you're right, that was a rant, I apologize. Will edit the comment. And thanks for pointing me in the right direction.
