### ISSUE TITLE
target server for DNS probe

### ISSUE THREAD

**Issue by smallgreenhorse** [prometheus/blackbox_exporter#300]
Can DNS probe be extended to allow specify DNS server to which to send the query ?
I think https://github.com/miekg/dns does support this.

**Comment by brian-brazil** [comment]
Yes, that's the whole point of the DNS probe. It's the target URL parameter.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
