### ISSUE TITLE
Hosts gets converted to IP and makes request fail

### ISSUE THREAD

**Issue by elbryan** [prometheus/blackbox_exporter#303]
The request the blackbox exporter is making converts the hostname to IP in the request whilst I would like it to keep the hostname in the request itself. This comes to the fact that there is a proxy validating the request that needs the hostname to properly process it. In my specific case, the request times out.

Is it possible to disable resolving the DNS and to make the request "vanilla"?

### Host operating system: output of `uname -a`

Linux 2c16de9e1e0b 4.4.0-116-generic #140~14.04.1-Ubuntu SMP Fri Feb 16 09:25:20 UTC 2018 x86_64 GNU/Linux

### blackbox_exporter version: output of `blackbox_exporter -version`
0.12.0

### What did you expect to see?

`ts=2018-03-08T14:05:48.014991379Z caller=http.go:282 module=mymodule target=https://hostname/endpoint level=info msg="Making HTTP request" url=https://hostname/endpoint host=hostname
`
### What did you see instead?

`ts=2018-03-08T14:05:48.014991379Z caller=http.go:282 module=mymodule target=https://hostname/endpoint level=info msg="Making HTTP request" url=https://[IPADDRESS]/endpoint host=hostname`

**Comment by brian-brazil** [comment]
No, this is not possible. The blackbox exporter has to do resolution in order to implement v4/v6 selection logic. I'd suggest probing the backend directly.

**Comment by brian-brazil** [comment]
That works off the Host header, not the HTTP request line. That is handled correctly. Proxies where you're depending on the proxy for resolution will not work, we only have that parameter as it happens to come from the http library we use.

**Comment by vincepii** [comment]
So, when using the `blackbox_exporter` against any application that is behind an HTTP load-balancer, the user needs to specify the `Host` header or the request will just stop at the load balancer.

It's not extremely user-friendly as normally one would expect the `Host` header to be set based on the hostname in the URI.

I mean, normally people don't send requests with the `Host` header explicitly set:

```
curl -H "Host: vhost.host.domain.com" http://1.1.1.1
```

But just:

```
curl http://vhost.host.domain.com
```

and then find the `Host` header in the HTTP set to `vhost.host.domain.com`.

I think that, if you want to keep this behavior of translating hostname to IP in the URIs, a note in the documentation should at least be written, as many people will try to probe something behind a load balancer and fail, if they don't know that for that probe configuration the `Host` header should be explicitly set.

**Comment by vincepii** [comment]
Please disregard my comment as I just realized that you are actually setting the `Host` field in the HTTP request based on the original host (before the conversion to IP address).

**Comment by elbryan** [comment]
I have essentially deleted (and adjusted also the rest of the code) the following lines from the `http.go` file:

```
	// Replace the host field in the URL with the IP we resolved.
	origHost := targetURL.Host
	if targetPort == "" {
		targetURL.Host = "[" + ip.String() + "]"
	} else {
		targetURL.Host = net.JoinHostPort(ip.String(), targetPort)
	}
```

and now everything works flawlessly. @brian-brazil I don't understand how this affects the ip4/ip6 resolution. 

Do you think one of the following options are viable?

1. To just get rid of the code (in a proper PR)
2. To propose a PR with another option to send the request "vanilla"

**Comment by SuperQ** [comment]
@elbryan The problem is that if you remove the IP conversion, the Go `net/http` will do the DNS lookup and we lose the ability to control v4 vs v6.

**Comment by elbryan** [comment]
@SuperQ yeah, I finally understand that now. 😅 

What do you think if we had the ability of not resolving the DNS? I know that this feature is a bit silly (a properly configured proxy should work resolving the `Host` field) but it's currently a blocker for me.

**Comment by SuperQ** [comment]
I was looking over the Go upstream code, and some bug reports, there may be some low-level ways we can control the protocol family, but it would take some more investigation.  This might be worth it, as I'm not really a fan of the way we're currently handling v4 vs v6.

See: https://github.com/golang/go/issues/18422

**Comment by SuperQ** [comment]
I might support the idea of `ip4/ip6/none`.  I'm already thinking about implementing `ip4-only` as part of https://github.com/prometheus/blackbox_exporter/issues/302.

**Comment by brian-brazil** [comment]
Handling this upstream would be great, though I think we need to keep fallbacks in some form.

**Comment by JensErat** [comment]
This is a blocker for us -- we have an HTTP proxy as only interface to the internet, and even DNS requests to external domains are forbidden (probably to prevent leaking data through DNS tunnels). The only instance allowed to perform DNS requests to the internet is the HTTP proxy, with domains whitelisted.

This results in two issues:

- DNS not even resolvable so pushgateway fails at [`http.go:207`](https://github.com/prometheus/blackbox_exporter/blob/bedf262d644f5fa35f29a67b5b772c86ccd15e66/prober/http.go#L207), we were able to circumvent this by adding the domains and IPs to the `/etc/hosts` file through the Kubernetes Pod spec of pushgateway;
- The HTTP proxy expects the domain listed in the whitelist and not the IP address, so [`http.go:251`](https://github.com/prometheus/blackbox_exporter/blob/bedf262d644f5fa35f29a67b5b772c86ccd15e66/prober/http.go#L251) makes the request fail.

I have never seen any other application performing IP lookups when using HTTP proxies or had any issues with this setup, but we have to patch out the mentioned code blocks to be able to use the pushgateway. Surely our setup is a rather strict one, but I would not expect much of a difference in other companies.

My proposal would be to omit IP lookup when using proxies by default (to match other products when using HTTP proxies) and if testing IPv4/IPv6 specifically, make the lookup an option.

Since this issue and required changes are still discussed -- should it be reopened?

**Comment by JensErat** [comment]
If you do not implement HTTP proxies in the usual way (by the way, in #264 brought up the exactly same statement "I would never expect an HTTP proxy client to perform DNS resolution (of anything but the proxy's hostname itself). That's not how HTTP proxies are supposed to work.". _At least_, this is something that must be documented. Neither can I find any statement in the documentation that blackbox exporter is supposed to be used in your local network -- something at least I would consider surprising given the feature set.

**Comment by dabear** [comment]
Hi. Any updates here? It is quite a common use case for us to use proxy, as ip addresses on certain hosts change frequently (sites hosted by aws and azure don't necessarily have static ips). It makes it kinda hard to use blackboxexporter to monitor such sites, in an otherwise locked down environment.

**Comment by brian-brazil** [comment]
> (sites hosted by aws and azure don't necessarily have static ips)

If you've evidence that we're disobeying DNS TTLs, please file a bug.

**Comment by dabear** [comment]
Hi, DNS resolution isn't the problem. We have a very locked down environment. Having to update the proxy whitelist with new ips when they change is a serious problem for us. That's why we need blackbox to be able to use hostname rather than ip. using the hostname header isn't good enough, because proxies such as squid can't use that for verification against it's whitelist.

**Comment by raypettersen** [comment]
This is becoming crucial for our monitoring.

**Comment by Morriz** [comment]
Any update on this? We can test a lot of urls correctly behind an AWS ALB, but only if they have one ssl cert, so for single domains only. If we probe other ALBs hosting many domains, then it barfs that it can't match the ip with any CN.

I could not get insecure_skip_verify to work btw. My config:
```yaml
modules:
  http_2xx:
    http:
      no_follow_redirects: false
      preferred_ip_protocol: ip4
      tls: true
      tls_config:
        insecure_skip_verify: true
      valid_http_versions:
      - HTTP/1.1
      - HTTP/2
    prober: http
    timeout: 5s
```
