### ISSUE TITLE
How to probe "x509: certificate signed by unknown authority" with ssl_earliest_cert_expiry metic?

### ISSUE THREAD

**Issue by rajivmucheli** [prometheus/blackbox_exporter#316]
Hi,

I have perfect blackbox_exporter working in my local, i am working on ssl_earliest_cert_expiry metric to get certificate expiry details from host which use `x509: certificate signed by unknown authority`. I get the below error : 

msg="Error for HTTP request" err=x509: certificate signed by unknown authority"
level=error msg="Final request was not over SSL"

Due to the above, i am unable to achieve the task. I presume this happens since its falling back to HTTP module, is there a HTTPS module? would be great to hear better suggestions on how to achieve this task, thanks.

Regards,
Rajiv

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
