### ISSUE TITLE
How can do this ?

### ISSUE THREAD

**Issue by TheCardiall** [prometheus/blackbox_exporter#328]
Hi,

I have a fleet of 800 VM how can I monitor about 5 ports per VM? 
Is there a way to include? If yes, how ?

Thank you for your help

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
