### ISSUE TITLE
Usage with prometheus / kubernetes and auto discovery

### ISSUE THREAD

**Issue by DenisBiondic** [prometheus/blackbox_exporter#330]
Is it possible to use blackbox exporter by simply exposing it over a kubernetes service and using prometheus auto discovery to automatically pull all metrics from its /metrics endpoint?

**Comment by brian-brazil** [comment]
Yes, that's possible. It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
