### ISSUE TITLE
Blackbox exporter load handling capability

### ISSUE THREAD

**Issue by krdineshbny** [prometheus/blackbox_exporter#336]
Hi all
we are currently using prometheus and blackbox setup in our organization.
We are planning to expand the use of blackbox further.
Inorder to do this we are testing the blackbox with 50K URLs and scrape interval 2mins and timeout 60secs.
We see multiple timeouts with context deadline exceeded error,when we scaled from 20K to 50K.
May i know how much urls can be probed by Blackbox exporter.
And how the probes are checked concurrently is it FIFO or follow any other pattern.
Any insights in this regards is highly appreciable.
@brian-brazil 
Regards
Dinesh KR

**Comment by brian-brazil** [comment]
The blackbox exporter hasn't been stresstested recently, but should be able to handle that load. Make sure you're using a big enough machine. You can always load balance across several.

**Comment by vivekbny** [comment]
the machine we use is quite big. 
@brian-brazil how the probes are checked concurrently? is it FIFO or follow any other pattern.

**Comment by SuperQ** [comment]
Prometheus schedules scrapes using a threaded model, distributed evenly over the scrape interval.

The blackbox exporter is also multi-threaded, handling everything requested in parallel.

For usage questions/help, please use our [community](https://prometheus.io/community/).  There are many more people there that can help.  GitHub issues are reserved for bug reports and feature requests.

**Comment by vivekbny** [comment]
Thanks @SuperQ. Going forward will reach out to the community for the help.

I am trying to enable the log level to debug for the exporter by passing args **--log.level debug**. But it does show only info log.

Can you please advise on enabling the debugging log for the BB exporter

**Comment by vivekbny** [comment]
@brian-brazil @SuperQ Can you please advise on enabling the debug flag for the BB exporter.

Earlier we used to pass  --log.level debug in args which no more works

Thanks,
Vivek

**Comment by dswarbrick** [comment]
I have recently started to notice unexpectedly high CPU time used by blackbox, considering that it spends the majority of its time waiting for IO from the remote endpoint. I ran a CPU pprof on it, and the thing that sticks out is the amount of time spent allocating and garbage collecting, associated with `compress/flate.NewWriter`.

I am aware that the popular https://github.com/NYTimes/gziphandler uses `sync.Pool` and reuses the gzip Writers by calling `Writer.Reset()`. This allows it to be used for a new underlying io.Writer, and avoids the expensive `gzip.NewWriter()` call each time. https://github.com/grpc/grpc-go also implements this technique.

A quick glance at https://github.com/prometheus/client_golang would appear to indicate that it does not pool the gzip Writers, so my casual assumption is that the CPU time is burned by client_golang, not blackbox. It's understandable that this hasn't been a priority for client_golang, since most exporters do not experience a high rate of requests. Due to the nature of blackbox however, I suspect it would be a good idea to implement pooled Writers.

**Comment by SuperQ** [comment]
@dswarbrick Thanks for looking into it. Maybe it's worth bringing this up on the client_golang repo? I know @beorn7 has been working on improvements there.

**Comment by dswarbrick** [comment]
@SuperQ @beorn7 It looks like somebody else already came to the same conclusion in https://github.com/prometheus/client_golang/issues/366. Maybe it's worth reopening that issue and implementing a gzip Writer pool.

**Comment by beorn7** [comment]
Done. :o)

**Comment by viniciuscps** [comment]
> Hi all
> we are currently using prometheus and blackbox setup in our organization.
> We are planning to expand the use of blackbox further.
> Inorder to do this we are testing the blackbox with 50K URLs and scrape interval 2mins and timeout 60secs.
> We see multiple timeouts with context deadline exceeded error,when we scaled from 20K to 50K.
> May i know how much urls can be probed by Blackbox exporter.
> And how the probes are checked concurrently is it FIFO or follow any other pattern.
> Any insights in this regards is highly appreciable.
> @brian-brazil
> Regards
> Dinesh KR


Hi, could you help me with the configuration? I'm trying, but so far I only received the message "DOWN"
My intention is to collect 2xx 4xx 5xx messages and also log in / password (I saw a demo and I want to implement this check in the website), but first I have to make the 2xx checks work. If you can help me, I thank you!

**Comment by brian-brazil** [comment]
This was handled over in client_golang.
