### ISSUE TITLE
On monitoring DNS parsing address and return time

### ISSUE THREAD

**Issue by peixiaoqing** [prometheus/blackbox_exporter#403]
system：centos7.4
kernel： Linux test 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Problem description：
Hello, I would like to monitor the return time of DNS and the resolved DNS address, according to the template configuration, but found no return DNS address, how to configure, whether there is a specific configuration template? The following screenshot is the configuration screenshot
![blackbox yml](https://user-images.githubusercontent.com/35130532/50620911-7f058280-0f3d-11e9-8bcc-7beadb946f71.jpg)
![prometheus yml](https://user-images.githubusercontent.com/35130532/50620913-82990980-0f3d-11e9-85a6-e158da1ed75a.jpg)
![return result](https://user-images.githubusercontent.com/35130532/50620990-f0ddcc00-0f3d-11e9-86b4-09127bb02d06.jpg)

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
