### ISSUE TITLE
How to enable or change log level in config files

### ISSUE THREAD

**Issue by ybiconviva** [prometheus/blackbox_exporter#408]
Could you provide me an example on how to enable or change blackbox's log level in config files?

https://github.com/prometheus/blackbox_exporter/blob/master/example.yml

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by ybiconviva** [comment]
I thought this will induce an example code change, anyway, I will ask for help from mail group.

获取 Outlook for iOS<https://aka.ms/o0ukef>

________________________________
发件人: Brian Brazil <notifications@github.com>
发送时间: 星期四, 一月 17, 2019 8:45 下午
收件人: prometheus/blackbox_exporter
抄送: Yan Bi; Author
主题: Re: [prometheus/blackbox_exporter] How to enable or change log level in config files (#408)


Closed #408<https://github.com/prometheus/blackbox_exporter/issues/408>.

―
