### ISSUE TITLE
How to relabel source labels -> Header ?

### ISSUE THREAD

**Issue by zhangguanzhang** [prometheus/blackbox_exporter#414]
In the http_prober,  I want to use relabel to set the values of the http request's header? or something else could I did this

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
