### ISSUE TITLE
Monitor how ICMP grabs lost packets

### ISSUE THREAD

**Issue by peixiaoqing** [prometheus/blackbox_exporter#422]
Hello there:
Dear developer:

Prometheus version: 2.0.0-beta.2
Grafana: 5.2.3
Black_box: 0.13.0

How can I monitor the icmp packet loss situation using prometheus? At the moment we tested it, we found that the packet loss was shown as a delay. How do you write a statement?
A few seconds are all packet loss, but the monitoring shows a delay of a few seconds.

![default](https://user-images.githubusercontent.com/35130532/53384376-9dc04c80-39b5-11e9-9feb-9b60fce2705e.png)
The following figure is the query statement
![default](https://user-images.githubusercontent.com/35130532/53384443-e4ae4200-39b5-11e9-8d0c-941b0c57b4a6.png)

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
