### ISSUE TITLE
whait is mean the tls ?

### ISSUE THREAD

**Issue by kelonsen** [prometheus/blackbox_exporter#463]
```
probe_http_duration_seconds{phase="resolve"} 0.023038304
probe_http_duration_seconds{phase="connect"} 0.004941385
probe_http_duration_seconds{phase="processing"} 0.005904898
probe_http_duration_seconds{phase="tls"} 0.015312129
probe_http_duration_seconds{phase="transfer"} 0.000189544
```

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
