### ISSUE TITLE
[Feature Request] Specify multiple IP's for each target

### ISSUE THREAD

**Issue by Morzain** [prometheus/blackbox_exporter#473]
Monitoring SSL certificates directly is easy by just listing the targets:

`- job_name: ssl_check
  scrape_interval: 5m
  metrics_path: "/probe"
  params:
    module:
    - http_2xx
  static_configs:
  - targets:
    - https://example.com
`

But when that target is behind a load balancer, we are only testing the LB itself and not all the nodes behind it. If we were to change it to the IP's of the nodes we may get the wrong certificate as we are not passing the domain via SNI

Ideally we could a list of IP's for each target:

`
- job_name: ssl_check
  scrape_interval: 5m
  metrics_path: "/probe"
  params:
    module:
    - http_2xx
  static_configs:
  - targets:
    - https://example.com
         ip: 127.0.0.1
         ip: 127.0.0.2
         ip: 127.0.0.3
`

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
