### ISSUE TITLE
Some enhancements in probe_http_status_code and probe_success

### ISSUE THREAD

**Issue by vovkanaz** [prometheus/blackbox_exporter#486]
Hello, seems like Prometheus for some reasons can't calculate all successful or failed metrics count based on probe_success and probe_http_status_code. Examples:
`sum(increase(probe_success{instance=~"$target"}[1h]))` result --> 0
`count(sum(increase(probe_http_status_code{instance=~"$target"}[1h])))` result --> 0
Also, it would be grate to have possibility to add something like error-status definition in query of the metric:
`**count(sum(increase(probe_http_status_code{instance=~"$target", code=~'5..'}[1h])))**`
There a lot of teams use this amazing tool for SRE goals (SLI,SLO calculations Error Budgets).
So it would be great if you'll implement such features, or just explain some workaround  - how to get a whole count of successful/failed requests pet time period.
Thanks in advance

**Comment by brian-brazil** [comment]
This is a PromQL question. It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
