### ISSUE TITLE
Url monitoring group in different folder or dashboard

### ISSUE THREAD

**Issue by ajayakumar-jayaraj** [prometheus/blackbox_exporter#498]
### What did you expect to see?
Group of url monitors on different dashboard or failure urls on top of list. When I want to monitor 50+ url it would be difficult to have tab on all urls

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
