### ISSUE TITLE
How to Count/Sum "probe_duration_seconds" over threshold we defined

### ISSUE THREAD

**Issue by thachnv92** [prometheus/blackbox_exporter#500]
Hello,

I setup blackbox exporter to monitor our APIs.
I get **Response Time** by metric **"probe_duration_seconds"**
Could I **COUNT** or **SUM** number which "probe_duration_seconds" **over threshold we defined**?
Example:
I defined threshold is 500 ms.
I need to COUNT number of Response Time over 500 ms.
OR COUNT number of Response Time over 500 ms.

Please help me.
Thanks.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by thachnv92** [comment]
Thanks

**Comment by iAlexMlops** [comment]
I think it's bad form to leave a problem unresolved, given that the letter also received no response.

I tried this formula:

`count_over_time((probe_http_status_code{instance="foo"}==200)[$__range:]) / count_over_time(probe_http_status_code{instance="foo"}[$__range:]) * 100`
