### ISSUE TITLE
Query not working

### ISSUE THREAD

**Issue by MiguelNdeCarvalho** [prometheus/blackbox_exporter#501]
Hey, 
Basically I am trying to do a query that sees if both Websites are running, if yes it return "ALL OKAY" if not it returns "SOMETHING WRONG". Query that I am trying to use `(probe_success{instance="http://angulosolido.pt/",job="blackbox",module="http_2xx"}) and (probe_success{instance="https://nextcloud.miguelndecarvalho.pt/",job="blackbox",module="https_2xx"})`. I thought that it works like a AND, basically if both are 1 (UP) it will return 1 too.
Thanks,
Miguel de Carvalho

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
