### ISSUE TITLE
DNS prober: Target nameserver(s) in resolv.conf

### ISSUE THREAD

**Issue by mattbostock** [prometheus/blackbox_exporter#52]
I'd like to add support to the DNS prober to be able to query nameservers in resolv.conf.

The [dns library](https://godoc.org/github.com/miekg/dns) used by the DNS prober [supports parsing resolv.conf](https://godoc.org/github.com/miekg/dns#ClientConfigFromFile), which is useful for emulating whether an application in userspace that relies on resolv.conf can successfully query a specified DNS record.

Some considerations to work out:

- Should the DNS prober return a success if just one of the nameservers from resolv.conf succeeds? I think yes.
- How should resolv.conf be defined as a target? Using a magic string constant specified in the query string? See related issue: #51

**Comment by brian-brazil** [comment]
The intention of the dns module is that you're testing a particular DNS server.

If you want to test something more high level, then you probably want to use one of the other modules which will implicitly use resolv.conf.

**Comment by mattbostock** [comment]
@brian-brazil In this case, I want to check that specific DNS records are able to resolve using the system resolver, so as to emulate whether a node can resolve those records. Using something like ping is not ideal as you're no longer testing DNS resolution alone and it doesn't work well for `TXT` or `SRV` records.

**Comment by knyar** [comment]
Keep in mind that parsing `resolv.conf` and probing resolvers defined there is not strictly representative of "whether a node can resolve", since I believe most binaries would normally use `glibc`-provided `getaddrinfo` / `gethostbyname`, which go through NSS. There are some exceptions, obviously, like `net` module in Go reimplementing its own resolving, but even it falls back to `getaddrinfo` if needed.

What I am trying to say is that writing a custom probe might be more appropriate for this use case than modifying the DNS prober in blackbox_exporter.

**Comment by mattbostock** [comment]
That's reasonable. We can pass the same nameserver specified in configuration management for nameservers.conf to blackbox_exporter, which might be a cleaner solution.
