### ISSUE TITLE
Whether the blackbox exporter support ipv6 detection?

### ISSUE THREAD

**Issue by neet11** [prometheus/blackbox_exporter#542]
I have configured IPv6 address in Prometheus, and return 403 through blackbox detection, probe_success = 0,But it returns 200ok by  curl this IPv6 address directly , and Ping is also OK.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
