### ISSUE TITLE
How do I start up in the background in Windows

### ISSUE THREAD

**Issue by for-mat** [prometheus/blackbox_exporter#559]
I created the service on Windows, but the startup times were wrong
error 1053 The service did not respond to startup or control requests in a timely manner

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by nadme92** [comment]
> I created the service on Windows, but the startup times were wrong
> error 1053 The service did not respond to startup or control requests in a timely manner

I have exactly the same problem have you find a solution ? thanks
