### ISSUE TITLE
http2 support?

### ISSUE THREAD

**Issue by psy-core** [prometheus/blackbox_exporter#560]
Is blackbox exporter ready to support http2 protocol?

**Comment by brian-brazil** [comment]
It should just work, as we're using a new enough version of Go.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by Sebi2020** [comment]
By default the docker image outputs:
```
 caller=tls_config.go:191 msg="TLS is disabled." http2=false
```

**Comment by SuperQ** [comment]
That is for the web UI, not the probes. it can be configured with a [web config](https://github.com/prometheus/exporter-toolkit/blob/master/docs/web-configuration.md).
