### ISSUE TITLE
How do I detect a status code of 301,302

### ISSUE THREAD

**Issue by caoxiaojian** [prometheus/blackbox_exporter#562]
blackbox.yml
 
 web_3xx:
    prober: http
    timeout: 10s
    http:
      preferred_ip_protocol: "ip4" 
      valid_status_codes: [301,302]

I would like to test the status code 301,302, using the above configuration file, blackbox_exporter can run, corresponding to the status code 301 domain name, Prometheus shows 0, not 1.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by raxod502-plaid** [comment]
To help future readers, the answer is here: https://groups.google.com/g/prometheus-users/c/N6C7SezQmGY/m/e9dqjRFLAQAJ

You must include `no_follow_redirects: true` in your exporter configuration. An example is here: https://github.com/prometheus/blackbox_exporter/issues/243
