### ISSUE TITLE
blockbox is not support traefik ingressRout

### ISSUE THREAD

**Issue by dd01panqinglong** [prometheus/blackbox_exporter#564]
blockbox not can use in traefik crd explames traefik IngressRoute

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
