### ISSUE TITLE
Feature request icmp loss mtr

### ISSUE THREAD

**Issue by tyit** [prometheus/blackbox_exporter#565]
icmp loss triggers mtr to track IP routes Alert

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
