### ISSUE TITLE
Feature Request: Is there a way to scrape "Probe Logs" 

### ISSUE THREAD

**Issue by birmogave87** [prometheus/blackbox_exporter#586]
I want to be able to query the values that Probe Logs have when requsting a GET or a POST request: For example: 
Response timings for roundtrip" roundtrip=0 
start=2020-03-25T03:35:13.715468308Z 
end=2020-03-25T03:35:13.865802576Z
module=http_post_2xx 
target="URL" 
duration_seconds=0.15102186. 

I was not able to user PromQL and see this mertices pop up. Any suggestions.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
