### ISSUE TITLE
Blackbox exporter probe_ssl_earliest_cert_expiry giving wrong value in grafna

### ISSUE THREAD

**Issue by pir8g33k** [prometheus/blackbox_exporter#607]
I have configured and installed blackbox exporter to monitor application url and SSL expiry in grafana dashboard , I see the SSL expiry is showing wrong

probe_ssl_earliest_cert_expiry{instance=~"$target"} -time()

but on priometheus panel i was able to get the correct data of expiration.
![githubbbexporter](https://user-images.githubusercontent.com/63558386/80082488-09d11d00-8587-11ea-955c-e1fc23310b3e.PNG)
![giithubstatus](https://user-images.githubusercontent.com/63558386/80082494-0b9ae080-8587-11ea-9245-19cfefe9841b.PNG)

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by pir8g33k** [comment]
Thank you Brian noted on this
