### ISSUE TITLE
Blackbox to telnet

### ISSUE THREAD

**Issue by mrdavidaylward** [prometheus/blackbox_exporter#615]
HI,

We using BlackBox to do our monitoring.
We've noticed that when BlackBox is pointed at telnet or SNTP with the TCP module it closes the connection with a reset instead of a graceful close, which it does for other TCP ports. These resets show up as errors in our other systems, is there a config or something we can add to have this close with a fin and not a reset.

![WhatsApp Image 2020-05-08 at 12 42 07](https://user-images.githubusercontent.com/60498357/81401739-3a40bb80-9130-11ea-8eed-55de3574db82.jpeg)

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
