### ISSUE TITLE
http prober allows forcing DNS resolution like curl --resolve

### ISSUE THREAD

**Issue by mmb** [prometheus/blackbox_exporter#621]
We have a hostname that resolves to different IP addresses around the world. It would be great if we could monitor all of them with blackbox by forcing the name to resolve to an IP specified in the probe config.

**Comment by brian-brazil** [comment]
That's a matter of passing in the IP you want as the target. 
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by mmb** [comment]
I considered it more of a feature request but I can follow up on the mailing list.

Using the IP as the target is not the same as using a hostname and forcing the name resolution. It won't work with SNI for example. Unless there is some way to use the IP as the target and specify a hostname?

**Comment by mmb** [comment]
I see it now in tls_config / server_name. Thanks!

**Comment by blessendor** [comment]
> I see it now in tls_config / server_name. Thanks!

Can you share your config for example? I'm looking for similar solution. 
I need ti check the product page url, use some regexp through its content, and sen this url request to the NGINX IP address, instead of via CloudFlare Proxy.

**Comment by mmb** [comment]
I don't have access to the code any more but I believe I used the IP addresses as the targets and set the tls_config / server_name to the shared hostname to make SNI work.
