### ISSUE TITLE
Monitor cluster from operator via blackbox exporter

### ISSUE THREAD

**Issue by JennyMet** [prometheus/blackbox_exporter#660]
This is not an issue but rather support.

We have several K8S clusters which we need to monitor from one operator cluster (cluster A) We are using Prometheus on each cluster to monitor the cluster, now in addition we want to monitor from one operator cluster other cluster

    Cluster A (operator) should monitor other cluster B

e.g. by calling K8S API server to see that status - from the operator cluster call to the API server via some rest call and keep the data in Prometheus (in operator cluster).

Is it possible to do it with blackbox exporter, currenlty the issue I see is if I provide the endpoint (url) , how should I provide also the **kubeconfig** of the monitored cluster ?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by JennyMet** [comment]
@brian-brazil  - thanks will do it.
