### ISSUE TITLE
nginx-ingress-controller.ingress-nginx.svc:80	Failure.   what happen?

### ISSUE THREAD

**Issue by reaperhero** [prometheus/blackbox_exporter#664]
![image](https://user-images.githubusercontent.com/43801667/87423681-47d16080-c60d-11ea-8550-0216acb15dae.png)

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
