### ISSUE TITLE
Old probe sites still appear after removing

### ISSUE THREAD

**Issue by andywhiteglobal** [prometheus/blackbox_exporter#670]
Hello,

I've got Blackbox running to monitor a few external sites.  I am running Grafana 7.1 on Ubuntu with InfluxDB and Prometheus.

I've added a Dashboard I downloaded from https://grafana.com/grafana/dashboards/5345

I had to remove 2 sites from my prometheus.yaml file but they still appear abeit no data showing since the time I removed from the yaml file.  They don't even appear in http://prometheusvm:9090/targets

I'm not sure where it's pulling the old website names from, they still show in the drop down menu too.

Any ideas?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
