### ISSUE TITLE
Installation on Windows 

### ISSUE THREAD

**Issue by herland** [prometheus/blackbox_exporter#695]
I created the service with the following parameters:

C:\Data\blackbox_exporter\blackbox_exporter.exe --config.file=C:\Data\blackbox_exporter\blackbox.yml 

I have the following error at startup:: The service did not respond to the start or control request in a timely fashion.

has someone installed the service on windows?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by herland** [comment]
grazie mile
