### ISSUE TITLE
various blackbox exporter in the same job

### ISSUE THREAD

**Issue by josefoSe** [prometheus/blackbox_exporter#702]
Hello friends, I am trying to configure in the same job several blackbox_exporters that must run local on the servers but it does not work out.
   - job_name: 'a_html'
     scrape_interval: 10m
     metrics_path: / probe
     params:
       module: [http_2xx] # Look for a HTTP 200 response.
     static_configs:
       - targets:
         - https://127.0.0.1:443/a.html # Target to probe with https.
     relabel_configs:
       - source_labels: [__address__]
         target_label: __param_target
       - source_labels: [__param_target]
         target_label: instance
       - target_label: __address__
         replacement: server1: 9115 # The blackbox exporter's real hostname: port.
       - target_label: __address__
         replacement: server2: 9115 # The blackbox exporter's real hostname: port.
please help me

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
