### ISSUE TITLE
Can we use black box exporter to hit url for verifying SSO kind of logins instead of basic authentication

### ISSUE THREAD

**Issue by ravikumar2000** [prometheus/blackbox_exporter#709]
Hi,

We have a requirement to hit a form based URL with username and password credentials and signin button. Verify the url with credentials using blakbox exporter.
Is the black box exporter will have redirection of url example
http://abc.com------> will redirect to SSO or other url which has username and password page.
Let us know can we test these requirements in black box exporter or any other exporter

Regards,
Ravi

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
