### ISSUE TITLE
Can't start blackbox using go run command

### ISSUE THREAD

**Issue by kotyara85** [prometheus/blackbox_exporter#710]
### Host operating system: output of `uname -a`
macos
### blackbox_exporter version: output of `blackbox_exporter -version`
0.18.0

```
$ go run main.go
# command-line-arguments
./main.go:70:100: undefined: resultHistory
./main.go:210:9: undefined: resultHistory
```

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
