### ISSUE TITLE
Specify HTTP version in requests

### ISSUE THREAD

**Issue by pelov** [prometheus/blackbox_exporter#726]
### blackbox_exporter version:
```
blackbox_exporter, version 0.18.0 (branch: HEAD, revision: 60c86e6ce5a1111f7958b06ae7a08222bb6ec839)
  build user:       root@53d72328d93f
  build date:       20201012-09:46:31
  go version:       go1.15.2
```
### What did you expect to see?

An option to configure for each http probe which HTTP version to use, e.g. 1.1, 2.0, auto, ...

### What did you see instead?

The http probe uses HTTP/2 by default which in some situations may not be the right choice even if the server supports it.

I see that in the latest version 0.15.0 of prometheus/common, the functions that initialize the HTTP client have an extra argument `enableHTTP2`. So, whenever you upgrade the blackbox exporter to this version of prometheus/common you need to support this option in one form or another. Just curious if you have any plans how to go about that? I could possibly help with a PR if you give any directions?

**Comment by brian-brazil** [comment]
> I see that in the latest version 0.15.0 of prometheus/common, the functions that initialize the HTTP client have an extra argument enbleHTTP2.

That's a temporary workaround for HTTP/2 brokenness in Go, which happens to not affect this exporter so that parameter is to allow HTTP/2 probing here. 

> So, whenever you upgrade the blackbox exporter to this version of prometheus/common you need to support this option in one form or another.

It'll be hardcoded to true. This is internal-only, and this particular parameter will never be configurable by users.

> I could possibly help with a PR if you give any directions?

Any change here also affects Prometheus and the Alertmanager, and I don't think it makes sense to have that configurable there as that'd imply a broken HTTP endpoint.

> An option to configure for each http probe which HTTP version to use, e.g. 1.1, 2.0, auto, ...

Go doesn't allow for that, you get either 1.1 or 2.0. If you need more specific probing than that in Go, you'll need to hand-code a HTTP client. The tcp probe may be of use for that.

**Comment by pelov** [comment]
Of course, such an options should be either 1.1 or 2.0. And it seems it could be added only to the http prober of the blackbox exporter without affecting Prometheus or Alertmanager.

Anyway, this is probably again a niche feature so feel free to close it.

**Comment by brian-brazil** [comment]
> And it seems it could be added only to the http prober of the blackbox exporter without affecting Prometheus or Alertmanager.

Not really, the code and config structure is shared. This is all a black box to this code.
