### ISSUE TITLE
how to use dns modules to test my DomainName

### ISSUE THREAD

**Issue by kof8855** [prometheus/blackbox_exporter#734]
i want to test a domainname like www.aaaaa.top and get success result A (Address) 

who can give me a example 
how to config  blackbox.yml
how to config  prometheus.yml

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
