### ISSUE TITLE
DNS probing performance regression in 0.19.0

### ISSUE THREAD

**Issue by yegle** [prometheus/blackbox_exporter#791]
I run blackbox-exporter in docker probing a DNS server in another docker container.

With cache on DNS server end, probing latency is usually ~120us at 0.18.0. After updating to 0.19.0 it jumps to ~450us.

Knowing my patch in https://github.com/prometheus/blackbox_exporter/issues/724 I updated my config with `preferred_ip_protocol: "ip4"` since I don't configure ipv6 in my docker network, but it still result in ~200us latency.

Reverting back to 0.18.0 and now I have consistent ~120us latency again.

**Comment by karlism** [comment]
I'm seeing similar degradation in my environment too, `blackbox_exporter` was updated on May 19th and since then `probe_dns_duration_seconds{phase="resolve"}` and `probe_http_duration_seconds{phase="resolve"}` has increased significantly:
<img width="951" alt="image" src="https://user-images.githubusercontent.com/19568035/119474914-ee69b000-bd4c-11eb-92d9-8ee8d64a7bdd.png">
<img width="951" alt="image" src="https://user-images.githubusercontent.com/19568035/119474965-f7f31800-bd4c-11eb-8c8c-50e5f382767e.png">
All exporter VMs are running local instance of caching `dnsmasq` so DNS latency should be insignificant.

**Comment by SuperQ** [comment]
I wonder if this is related to https://github.com/prometheus/blackbox_exporter/pull/758

**Comment by yegle** [comment]
Presumably #758 only affects HTTP probing? It looks like the issue reported here is on DNS probing only.

**Comment by roidelapluie** [comment]
The issue is with https://github.com/prometheus/blackbox_exporter/issues/724

I think it might be related to the fact that we now compute the hash IN the resolve phase.

**Comment by roidelapluie** [comment]
Can you please test  https://github.com/prometheus/blackbox_exporter/pull/796 ?

**Comment by roidelapluie** [comment]
I will merge #796 soon but would still appreciate some testing.
