### ISSUE TITLE
Links on main page ignore the routePrefix value

### ISSUE THREAD

**Issue by lucabello** [prometheus/blackbox_exporter#814]
Hello,

I was deploying the blackbox exporter under something like `http://my.example.domain/blackbox`.
The pages are correctly placed under the proper path (e.g. `http://my.example.domain/blackbox/config`) and [main.go#L366](https://github.com/prometheus/blackbox_exporter/blob/5bad55cfb3fa6d09b0b58942977f1e59cdbc045e/main.go#L366) shows why:
```
http.HandleFunc(path.Join(*routePrefix, "/config"), [...]
```
However, the links for the main page are generated without taking the routePrefix in consideration; in [main.go#L331](https://github.com/prometheus/blackbox_exporter/blob/5bad55cfb3fa6d09b0b58942977f1e59cdbc045e/main.go#L331) we have:
```
<p><a href="config">Configuration</a></p>
```
AS you can see, the `href="config"` doesn't take the routePrefix in consideration, so it would lead to `http://my.example.domain/config` and thus to a 404 page not found error.

I'd be happy to create a PR to address this, but I thought opening an issue would be a good way to start.

Cheers,
Luca

**Comment by electron0zero** [comment]
not able to reproduce.

I started blackbox_exporter with `abc` prefix with `./blackbox_exporter --log.level=debug --web.route-prefix /abc` command, and the links on the homepage are correct, and works.

clicking on Configuration takes you to `http://localhost:9115/abc/config` because the href here is relative, and you are already at `http://localhost:9115/abc/`
