### ISSUE TITLE
MTR or traceroute module support?

### ISSUE THREAD

**Issue by qihonggang** [prometheus/blackbox_exporter#867]
Do you plan to support the MTR or traceroute module?

**Comment by dgl** [comment]
It doesn't really fit with blackbox_exporter, as traceroute is about more than seeing if something is up, there is a metric which might be useful in some cases `probe_icmp_reply_hop_limit`:
https://github.com/prometheus/blackbox_exporter/blob/master/prober/icmp.go#L80

Otherwise for questions/help/support please use our [community](https://prometheus.io/community/) channels. There are more people available to potentially respond to your request and the whole community can benefit from the answers provided.
