### ISSUE TITLE
CVE-2021-42377 reported in prom/blackbox-exporter:v0.19.0 

### ISSUE THREAD

**Issue by ggunawan** [prometheus/blackbox_exporter#879]
Our docker image scanning tools reported that prom/blackbox-exporter:v0.19.0 has CVE-2021-42377 with following description

> An attacker-controlled pointer free in Busybox's hush applet leads to denial of service and possible code execution when processing a crafted shell command, due to the shell mishandling the &&& string. This may be used for remote code execution under rare conditions of filtered command input.

Is it possible creating newer version of this image to resolve this CVE ?

**Comment by SuperQ** [comment]
An attacker would already have to be inside the container for this to be exploitable.

**Comment by electron0zero** [comment]
this should be fixed in recent release, going to close this due to age.

Please do not report [raw vulnerability scanner results](https://prometheus.io/docs/operating/security/#automated-security-scanners), most scanners are generic and produce lots of false positives and cause the Prometheus team toil in verifying each report.

Please verify vulnerability reports and include specific details as to which components and code paths are directly exploitable in the report.
